### ISSUE TITLE
RESTful form list without XML

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/central-backend#103]
`GET /formList` provides an XML list of available forms. `GET /forms` provides a similar json list but with full form XML included.

@tiritea suggests in Slack that a listing without XML through `/forms` would be helpful. Perhaps the form XML could be considered extended metadata.

**Comment by akshay-ap** [comment]
@lognaturel exactly in this format?
```
[{
   "formID": "SampleForm",
   "name": "SampleForm",
   "version": [],
   "hash": "md5:1c5966533b3d752d70546fb421a4ca8d",
   "downloadUrl": "http://localhost:8989F:\\v1/forms/TestRatingWidgetn.xml"
}
]
```

**Comment by clint-tseng** [comment]
No, it would be more like this:

```
{
        "createdAt": "2018-08-29T22:40:32.464Z",
        "hash": "357c5e3c8ab47e08b40b31869d70f490",
        "name": "Birds",
        "state": "open",
        "updatedAt": null,
        "version": ""
}
```

The only change is to leave the `xml` property out of the response unless `X-Extended-Metadata` is true.

**Comment by tiritea** [comment]
Thanks all. Being able to retrieve just the *list* - without all the bloated details - makes it so much faster to load a forms list for display onto a mobile device, from which a user can then make a selection, and only download the actual form (or submission...) when they explicitly select it. Otherwise essentially you have to download the entire full dataset just to display the list of items (which usually only displays summary/meta item data), which results in a much less responsive UI.
