### ISSUE TITLE
400 error when Collect is set to Spanish

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-backend#125]
Originally mentioned in the [ODK Forum](https://forum.opendatakit.org/t/odk-central-v0-2-beta/15005/6). @lognaturel says that she is seeing a 400 error when fetching blank forms if Collect is set to Spanish or French.

**Comment by lognaturel** [comment]
From https://forum.opendatakit.org/t/odk-central-v0-2-beta/15005/11:

> In relation with the date format, I was using the form "Formulario_basico". After setting the app language to English, i filled in a form. Then I changed the app language again to Spanish. When I sent the form I got the error: "An expected header field (Date) did not match the expected format....".

It sounds like the date sent in the OpenRosa header is localized in some way and that Central doesn't accept that.

**Comment by clint-tseng** [comment]
May I point out that I explicitly didn't want to implement the `Date` header field enforcement because I have absolutely no use for it, and that I am exactly following the OpenRosa spec?

**Comment by lognaturel** [comment]
Yup! Sounds like that was a mistake. I don't remember the exact conversation but this should be relaxed and I will add a note to the spec to make it clear the requirements don't seem to be followed by clients.

**Comment by lognaturel** [comment]
This is what Collect does:
```
GregorianCalendar g = new GregorianCalendar(TimeZone.getTimeZone("GMT"));
g.setTime(new Date());
req.setHeader(DATE_HEADER, DateFormat.format("E, dd MMM yyyy hh:mm:ss zz", g).toString());
```

The spec doesn't say anything about localization.

Example dates in different locales:
Date: Fri, 21 Sep 2018 08:03:35 GMT+00:00
Date: Dv, 21 Set. 2018 08:05:45 GMT+00:00
Date: शुक्र, 21 सित. 2018 08:06:42 GMT+00:00

I'm guessing servers typically check for something roughly like `abc, NN abc NNN NN:NN:NN GMT+NN:NN` or don't enforce a format at all. I don't have a strong feeling there.

**Comment by clint-tseng** [comment]
_sigh_, the spec says "in the format" and then instead of naming a format gives an example that is exactly HTTP date, which _is_ an [RFC standard (7231)](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) given precisely only in English.

I'm just going to remove the check altogether but I would strongly recommend amending the specification to use _some_ sort of standard or eliminate the check entirely. I've updated the [complaint doc](https://docs.google.com/document/d/1SrXS1CIKKhwLwXktfqLYtFgaUVQCFtw2a3qrmOr23KM/edit#).
