### ISSUE TITLE
Use form title rather than xmlFormId in submissions CSV filename

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-backend#177]
Briefcase uses the form title/name rather than the xmlFormId in the submissions CSV filename. (I think this was [mentioned briefly in #145](https://github.com/opendatakit/central-backend/issues/145#issuecomment-429879345).) This issue is to consider using the form title/name in Central as well.

**Comment by clint-tseng** [comment]
really? isn't it human readable? what if it's extremely long? isn't that exactly what we'd been worried about when we changed #145?

**Comment by matthew-white** [comment]
I think you're right that the form title is at greater risk of being long compared to the form ID: the form ID seems more suitable in that way. On the other hand, since Central and Briefcase are so close to exact consistency on the filename, it'd be nice to have the two align here as well. (Though I also think that consistency on this part of the filename matters much less than consistency in the repeat group names: the work in #145 was definitely the more impactful.)

With that in mind, three options come to mind:

1. Change Central to match Briefcase so that they both use the form title. (Does Briefcase truncate the form title if it's very long?)
2. Change Briefcase to match Central so that they both use the form ID. (Not sure whether this is practical. At the least, I'd guess that it probably couldn't ship until Briefcase 2.0.)
3. Let the two diverge on this point, since it probably matters less whether there's consistency on this part of the filename.

@clint-tseng, do you have a preference between these three options? I would lean toward (1) or (2) myself but would also be very fine with (3). CCing @ggalmazor as well.

**Comment by clint-tseng** [comment]
what does briefcase do when form title is not present? it's not required AFAIK.

**Comment by ggalmazor** [comment]
> what does briefcase do when form title is not present? it's not required AFAIK.

I believe it breaks :D
It uses the title to create the folders where the blank form, submissions and media files are stored locally.

> the form ID seems more suitable in that way

In my experience, it's not that good. Form IDs can be long and they have to be sanitized as well, which is annoying, but you can work around that. The real issue is that you can have dupes (more on that later).

> Does Briefcase truncate the form title if it's very long?

Nope. The impact of this in exported stuff's filenames has to be addressed in the future as well.

> 2. Change Briefcase to match Central so that they both use the form ID

I think we should rule out this option because using the form ID has proven to be problematic in the past. 

The real issue with form IDs and titles is that there can be dupes. Unless we implement restrictions on Central to avoid duped IDs or titles, this is going to bite us sooner or later.

Briefcase is going to address this problem by implementing a proper metadata database which will break our current coupling with either the form's ID or title. When this happens, "we will support dupes"-ish, and we will be free to decide however we want the filenames to be (both internal storage folders and files, and exported stuff)

**Comment by matthew-white** [comment]
I feel like the expectations around duplicate filenames might be different for Briefcase and Central. Briefcase creates a directory for each form, storing the form's data in that directory. There's perhaps the expectation that directories can persist and that once data for a form is exported, it doesn't have to be moved elsewhere. On the other hand, Central allows the user to download a single .zip file at a time (right now one .zip file per form, but in the future, perhaps one .zip file per project). Once it's downloaded, it ends up in the user's browser downloads location, where I think there's less expectation that its filename shouldn't conflict with other filenames: the user may need to move the .zip file from the downloads location to their own directory structure according to their specific workflow. Similarly, someone using the Central API will have to decide where to save the content of the .zip file according to their workflow.

I think it could still be a good goal to align Briefcase and Central filenames, in which case I think @clint-tseng is right that we should rename this issue and put it on hold. However, if we think there are different expectations around Briefcase and Central usage here, and it's less important that filename prefixes match between Briefcase and Central, I think it'd also be reasonable to have Central continue to use the form ID and for us to close the issue. @clint-tseng, @ggalmazor, what do you think?

**Comment by clint-tseng** [comment]
i think i'm going to close this for now and if any actual issues arise we can reopen it.
