### ISSUE TITLE
remove user roles when they are retired

### ISSUE THREAD

**Issue by issa-tseng** [opendatakit/central-backend#222]
with this change should come a migration which backfixes retired users by removing their roles.

**Comment by NizamLZ** [comment]
I went through the code and found that, when a user is deleted(assuming retired==deleted), we are setting the deletedAt field in actors table which marks the actor linked to the user as deleted. In order to   remove their roles, I was thinking that calling the actor.unassignRole() should do what we want.

By migration you mean, a new one which deletes all the role assignments of the previously deleted actors right?

**Comment by NizamLZ** [comment]
@opendatakit-bot claim
